# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6c13ad9e66ca9256190a7e130b85600d390aa00cc7acee552567af62179d80432177f3fc227db5c3fd34b8d90abf5098e5ed786434ab5f188f501ff9cf2fc04

test:
  secret_key_base: fd5b3bf82a45e3e1990a2c676ffe46de7180f5b2681e677a332f52c83c56e43917700cce434da0d5f5a778264c57ef83c7772f0feed39a0df1c1cbd32f0a54c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
